version: "3.8"
services:
  scraper:
    image: jkl453/hoerspiel-scraper:latest
    ports:
      - "5123:5123"
    volumes:
      - ${VOLUME_TARGET}/data:/app/data
    environment:
      PYTHONUNBUFFERED: "1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.scraper.entrypoints=http"
        - "traefik.http.routers.scraper.rule=Host(`${HOST_URL}`)"
        - "traefik.http.middlewares.scraper-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.scraper.middlewares=scraper-https-redirect"
        - "traefik.http.routers.scraper-secure.entrypoints=https"
        - "traefik.http.routers.scraper-secure.rule=Host(`${HOST_URL}`)"
        - "traefik.http.routers.scraper-secure.tls=true"
        - "traefik.http.routers.scraper-secure.service=scraper"
        - "traefik.http.services.scraper.loadbalancer.server.port=5123"
        - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true